services:
  api:
    build: .
    ports:
      - '3000:3000'
    environment:
      - PORT = 3000
      - GOOGLE_APPLICATION_CREDENTIALS=./gcp-keys.json
      - MONGODB_URI=mongodb://mongodb:27017/sentiment-analysis
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CACHE_TTL=60
      - CACHE_SIZE=100
    depends_on:
      - mongodb
      - elasticsearch
      - kibana
      - redis
    networks:
      - kibana-network
      - elasticsearch-network
      - mongo-network
      - node-network
      - redis-network

  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    networks:
      - kibana-network
      - elasticsearch-network
      - mongo-network
      - node-network
      - redis-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    environment:
      - discovery.type=single-node
    ports:
      - '9200:9200'
    networks:
      - kibana-network
      - elasticsearch-network
      - mongo-network
      - node-network
      - redis-network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.2
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - '5601:5601'
    networks:
      - kibana-network
      - elasticsearch-network
      - mongo-network
      - node-network
      - redis-network

  redis:
    image: redis:latest
    environment:
      - REDIS_HOST=localhost
    ports:
      - "6379:6379"
    networks:
      - kibana-network
      - elasticsearch-network
      - mongo-network
      - node-network
      - redis-network

networks:
  node-network:
    driver: bridge
  mongo-network:
    driver: bridge
  elasticsearch-network:
    driver: bridge
  kibana-network:
    driver: bridge
  redis-network:
    driver: bridge
