name: Deployment
run-name: Deploy to Master by @${{ github.actor }}

on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag sentiment-analysis-image:$(date +%s)
